### ISSUE TITLE
Work out spatial data access methods for GAP Species Ranges

### ISSUE THREAD

**Issue by skybristol** [usgs-bcb/gap_species#23]
Need a file option: dissolved seasonal range boundaries

Script to generate shapefiles with an example to be provided by @SGWilliams

**Comment by SGWilliams** [comment]
Here is the python script that exports range data as a dissolved shapefile and provides a full huc12 csv record of original data as well. Also included 3 examples of output.  The script relies on arcpy as well as gappage functions.

[bBOOWx_CONUS_KwnRng_2001v1.zip](https://github.com/usgs-bcb/gap_species/files/1380644/bBOOWx_CONUS_KwnRng_2001v1.zip)
[aRHSAx_CONUS_KwnRng_2001v1.zip](https://github.com/usgs-bcb/gap_species/files/1380645/aRHSAx_CONUS_KwnRng_2001v1.zip)
[bAMKEx_CONUS_KwnRng_2001v1.zip](https://github.com/usgs-bcb/gap_species/files/1380646/bAMKEx_CONUS_KwnRng_2001v1.zip)
[20170623SW_ExportRangeData.zip](https://github.com/usgs-bcb/gap_species/files/1380651/20170623SW_ExportRangeData.zip)

**Comment by skybristol** [comment]
@SGWilliams, I loaded up CSV files as one option on these to the 1719 species range items in the [collection](https://www.sciencebase.gov/catalog/item/5951527de4b062508e3b1e79). I'll rerun this as needed once we resolve the 0 code issue. Take a look at a few of the files there and let me know if they make sense.

We still have some work to do on the backend infrastructure with the GC2 platform where these data are sitting live that is causing the responses through the API to be way slower than they should be. Because we need to move this along, I opted to cache files on the ScienceBase items directly. We'll do the same thing with shapefiles if we can't get the dynamic output from MapServer working well enough.

I opted to keep the codes in the CSV tables as well as adding in the code values as I think that it makes sense to pass through exactly what's in the data in any output format we provide.

**Comment by SGWilliams** [comment]
Agreed on having both original codes and text for code values in the CSV. I looked at the content of two species (one wide spread with multiple seasons) and found an exact match on data in our local db. 

However, some things..

- strHUC12RNG must have been handled as numeric at some point and had a leading zero striped off. This could be fixed afterwards by evaluating the length of the field and concatenating a leading zero if equal to 11. Correct length is always 12.

- order of items should be (if possible);
_strUC
strHUC12RNG
intGapOrigin
intGapPres
intGapRepro
intGapSeas
Origin
Presence
Reproduction
Season_

- Edit of child purpose text:
"The known range for a species **_is_** used **_as a_** constraint the boundaries of the species distribution model...."

**Comment by skybristol** [comment]
Damn! I forgot to do the strHUC12RNG range fix here. Thanks for that.

I guess I'll work field ordering into a next iteration.

I'll fix the bad grammar in the purpose, but I think it would be useful to write it as not only the purpose to which we applied the ranges but as a purpose to which others might apply them.

**Comment by skybristol** [comment]
Species range CSV tables have been updated and are uploading now with a fix to the strHUC12RNG code as string with leading 0s added back in along with preferred field ordering. I still need to clean up text and some other attributes, including adding in the IUCN codes to both habitat and range maps that Leah provided.

I'm closing this particular issue out for now. Don Brown at FORT is working on spatial services, including the capability that will get us dissolved ranges by GAP attribute and shapefile downloads from the GC2 PostGIS/MapServer system where the data are loaded. Once methods are figured out and tested for performance, we'll put links onboard the items for access.
