### ISSUE TITLE
Range codes needing review

### ISSUE THREAD

**Issue by skybristol** [usgs-bcb/gap_species#29]
@SGWilliams and @nmtarr, as I have time, I'm working over some things with how we are storing and serving the species range data. I saw from the examples that @SGWilliams posted for how you all would like to package the data that you added code definitions/terms for the four different attributes on HUCs. I pulled the definitions you are using from the [gapproduction project](https://github.com/nmtarr/GAPProduction/blob/master/gapproduction/dictionaries.py) on @nmtarr. When I ran code to build a cache of the range data as CSV to the ScienceBase Items (now created [here](https://www.sciencebase.gov/catalog/item/5951527de4b062508e3b1e79)), I found some errant values that were not in your dictionary. I created [this notebook](https://github.com/usgs-bcb/gap_species/blob/master/Errant%20Species%20Range%20Codes.ipynb) to show you exactly where I found the issues. Can you look into this to see what needs to change - data or definitions?

I also found that you had "unknown" spelled "unkown" a few places and just fixed that in the set of code definitions I used.

**Comment by nmtarr** [comment]
@skybristol I corrected the dictionary and suspect that change will eliminate the problems.  Just let me know if it doesn't and I'll keep digging.  See my pull request.  I also corrected the dictionary in gapproduction.dictionaries.

**Comment by skybristol** [comment]
I think the dictionary/definition of the code values on this should be fine now. For future work on this, I incorporated the code lists into the ScienceBase Vocabulary, that you can hit with an HTTP request to return a JSON structure for working with in code (python or otherwise). For instance, here's the information for Origin codes and values.

https://www.sciencebase.gov/vocab/origin/terms?nodeType=term&parentId=59f602cae4b09d26336e76ed&max=10&offset=0&format=json

The ScienceBase Vocab is a pretty rudimentary system and not what we need in the long run. In these cases you need to find the code numbers in "name" and then use label and uri (and description if we made use of it). We will ultimately introduce some sort of more robust vocabulary server construct to the BIS, but for now, shoving some things into ScienceBase Vocab and starting to program against it where it makes sense will get us started. Other vocabularies/code lists sit in the system at [this level](https://www.sciencebase.gov/vocab/category/56327452e4b0a11afce68a88) and include things like the very specific ways that [GAP species tie to ITIS species](https://www.sciencebase.gov/vocab/bis_identifiers/terms?q=itis_tsn_&format=json).
