### ISSUE TITLE
Fix citation link to DOI in habitat map items and add citation to range items

### ISSUE THREAD

**Issue by skybristol** [usgs-bcb/gap_species#36]
The DOI link reference in the habitat map items is not a viable link, and we need to add a citation string to the items in the range maps collection

**Comment by SGWilliams** [comment]
Julie has stated that the links are not active but will be turned on at some point in the release process. The format is correct as far as we can tell.

**Comment by skybristol** [comment]
This is about the ScienceBase web links cross linking the habitat maps with the range maps. I put those on the range items but must have done something wrong because she found at least a few of them going to the wrong species habitat map.

You are correct on the DOIs. They are reserved in the system but not currently activated. We'll have to write some code to change those to active as we release the items.

**Comment by nmtarr** [comment]
I'm a little turned around on this issue.  I see the DOI in three places on habitat map items.  @skybristol would you clarify which ones are wrong and what they should be?  
1) in the citation they are this format:  https://doi:10.5066/F7319T7C
2) in the json document they are this format: https://doi.org/10.5066/F7319T7C
3) in the identifiers they are this format: doi:10.5066/F7319T7C

**Comment by skybristol** [comment]
The link string that was put into the citation is the part that was incorrect and generated this issue. I fixed those. The link format you used in the JSON document is just fine. That's what you'll see now in the citation string. The form that is in the identifier is also correct for that placement, which is really the "master" instantiation of the DOI for a given item.
