### ISSUE TITLE
Review species range CSV files

### ISSUE THREAD

**Issue by skybristol** [usgs-bcb/gap_species#38]
Someone should pull a random sample of [species range items](https://www.sciencebase.gov/catalog/item/5951527de4b062508e3b1e79) and check the accuracy and completeness of the CSV tables I generated on those items. I built these using the 4 source files that @SGWilliams provided, attached to the collection item. I added the values for the codes based on [these four vocabularies](https://www.sciencebase.gov/vocab/category/59f60211e4b09d26336e76eb) into the data along with the code numbers themselves.

These text files represent one way of getting at the data. We will be adding geospatial services and/or stashing an actual shapefile to the items based on work that @aulenbac is leading.

**Comment by SGWilliams** [comment]
I checked two (Falco sparverius (American Kestral and Alca torda (Razorbill) - they were spot on with data content.

I do see a lowercase genus for "ammadramus savannarum floridanus (Florida Grasshopper Sparrow)". I believe the creation of the child item names were run on an old species list before recent updates. You can find the corrected names in the HabMap SB item CSV file sent earlier. There will be several other name changes that are not so easy to spot (changing genus - there should only be one Spermophilus species present).

**Comment by McKerrow** [comment]
We are going to get Curtis to do a spot check of the csv files for a random set  with a few examples from each taxa.

**Comment by skybristol** [comment]
Well, dang. I'll have to run something against the update file across the board to make sure we pick up any changes. There was a lot based on scientific name and common name identifiers once those were set for the items. We'll need to change titles, citations, and other information bits.

@SGWilliams, could you replace the "Habitat Map Species Inventory" CSV file on [this item](https://www.sciencebase.gov/catalog/item/527d0a83e4b0850ea0518326) with the correct one that we should be using to make sure I'm operating on the same sheet of music.

**Comment by skybristol** [comment]
Great! Thank you @McKerrow for getting Curtis to take a look at the CSVs. Post any issues he finds, and we'll get them taken care of.

**Comment by SGWilliams** [comment]
"Habitat Map Species Inventory" CSV has been replaced with updated file. Here's a description of the table fields. Bold items have been updated. Some fields are new in comparison to Nathan's initial upload. At least one field has changed name. I won't bother describing pre-existing fields.

### ScienceBaseHabMapCSV_20171024.csv
GAP_code
_**common_name**_
_**scientific_name**_
start_date
end_date
publication_date
_**citation**_
place_keywords
_**theme_keywords**_
_**editor**_  (new - _modeler_ was dropped and replaced with _editor_ and _reviewer_)
_**reviewer**_  (new)
_**NatureServe_element_code**_
_**TSN_code**_
_**Global_SEQ_ID**_  (previously called _EGT_ID_)
input_data
IPDS
_**abstract**_
_**doi**_  (new - doi link)
ScienceBase_url  (new SB url)

**Comment by skybristol** [comment]
Great! Are there any attributes in this file that apply to both the habitat maps and the range maps (e.g., dates, editor, reviewer, etc.)? (I know that the NatureServe, etc. codes all apply.)

**Comment by skybristol** [comment]
Let's take the conversation on the item metadata out to #39 where I just posted a comment with specific reasoning on how I am treating the information in the spreadsheet. This issue can still be used to track comments on the review of the range data CSV files attached to the Range Map items.

**Comment by jpmagee** [comment]
@skybristol   Can I put (In Review) back in the title of this item https://www.sciencebase.gov/catalog/item/527d0a83e4b0850ea0518326  ? Just so we can easily distinguish it from the other item of the same name that is our public facing item that we are not putting new data into at this point.

**Comment by skybristol** [comment]
According to the audit history on the collection item, @SGWilliams changed the title.

"Fri Nov 03 12:46:04 MDT 2017 by sgwilliams@usgs.gov"

It's not that big a deal at this point, but @jpmagee, you and @McKerrow are really the owners of the collection level items for both Habitat Maps and Range Maps and should be the ones to handle those kinds of changes as we move forward toward review and beyond. I'm still working on changes at the item level as you've probably seen in recent code and the items themselves. As part of that I did ensure that the four source files we are using to drive what the items have in them were all correct, attached to the collection items, and read by my [code](https://github.com/usgs-bcb/gap_species/blob/master/Eval%20and%20correct%20all%20GAP%20habitat%20and%20range%20map%20items.ipynb) from there.

To all - I'd suggest that we let @jpmagee and @McKerrow handle any decisions about the root item information from here forward, and there are some changes that need to be made there now, including adding the (In Review) back in to the title.

**Comment by skybristol** [comment]
FYI - for authenticated users with write rights on the item, the audit log I referenced is available here:

https://www.sciencebase.gov/catalog/item/audit/527d0a83e4b0850ea0518326

**Comment by cbelyea** [comment]
We looked at 23 random species (5  from each taxa plus another 3 wide ranging). We compared data in the downloaded csv files to data extracted from the local database by joining strUC and strHUC12RANGE. For all 23 species, records matched exactly in terms of number of records and contents across all similar fields.

strUC | ComName | SciName
-- | -- | --
aRBNEx | Red-bellied Newt | Taricha rivularis
aHELLb | Ozark Hellbender | Cryptobranchus alleganiensis bishopi
aILGRx | Illinois Chorus Frog | Pseudacris illinoensis
aSGSSx | San Gabriel Mountains Slender Salamander | Batrachoseps gabrieli
aNTLSx | Northern Two-lined Salamander | Eurycea bislineata
bSPOWl | Mexican Spotted Owl | Strix occidentalis lucida
bWPWIx | Whip-poor-will | Caprimulgus vociferus
bLEYEx | Lesser Yellowlegs | Tringa flavipes
bGAQUx | Gambel's Quail | Callipepla gambelii
bGBTEx | Gull-billed Tern | Gelochelidon nilotica
mPRSHx | Prairie Shrew | Sorex haydeni
mLTSHx | Long-tailed Shrew | Sorex dispar
mCCDEx | Cactus Deermouse | Peromyscus eremicus
mSNHAx | Snowshoe Hare | Lepus americanus
mISFOc | Santa Catalina Island Fox | Urocyon littoralis catalinae
rYHGEx | Yellow-headed Gecko | Gonatodes albogularis
rFLSKx | Four-lined Skink | Plestiodon tetragrammus
rPRATx | Pygmy Rattlesnake | Sistrurus miliarius
rGPSLx | Graphic Spiny Lizard | Sceloporus grammicus
rFLBRx | Florida Brownsnake | Storeria victa
bAMKEx | American Kestrel | Falco sparverius
bAMROx | American Robin | Turdus migratorius
bREVIx | Red-eyed Vireo | Vireo olivaceus

**Comment by SGWilliams** [comment]
I finally had a chance to go back and look at what I did to edit the title of the collection record - which I certainly didn't intend to do. The only thing I can surmise is when I replaced the “Metadata Source: Habitat Maps” csv table it asked me about updating associated metadata records - and I assumed that it only pertained to this one file and said yes. Evidently, it pushes it out to the collection record as well. 

My apologies.

**Comment by skybristol** [comment]
Thank you, @cbelyea, for the spot check. I'm glad to see that the data all line up. I do have to rerun part of the process to take care of the couple of birds with issues identified previously, but then we should be good to go on the CSV end of this. @McKerrow will provide some guidance on the shapefiles, which we'll also want to run a check on, but I'll close this issue out for now.
